#!/bin/bash

set -e # exit on any errors

if [[ ! -r ./config-repo ]]; then
	echo "config-repo does not exist";
	exit 1
fi

REPO=$(cat ./config-repo | head -n1 | tr -d '\n');
KEY=$(cat ./config-repo | tail -n1);
KEY="keys/$KEY"

echo $REPO
echo "$KEY"
echo "Updating config from repo: $REPO using key: $KEY"

chmod 700 ./keys #7 or we can't do updates
chmod 400 $KEY

if [[ ! -r config/config.json ]]; then
	echo "Config not yet cloned..."
	ssh-agent bash -c "ssh-add $KEY; git clone $REPO config"
else
	if [[ -z config ]]; then
		mkdir config
	fi
	echo "Updating repo"
	cd config
	ssh-agent bash -c "ssh-add ../$KEY; git pull"
	cd ..
fi

./PiOn.php
